config/routes.rb
Rails.application.routes.draw do |map|
  
  match "/admin", :to => 'admin#index'
  
  resources :blogs do
    resources :articles
  end
  
  resources :namnder, :as => 'committees', :controller => 'committees'
    
  get "/kontakt/:slug" => 'contact#index', :as => 'contact'
  post "/kontakt/:slug" => 'contact#send_mail'
  
  resources 'kth-konton', :as => 'kth_accounts', :controller => 'kth_accounts'
  
  resources :morklaggning, :as => 'morklaggnings', :controller => 'morklaggnings'
  
  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/nyhetsbrev', :as => 'newsletters', :controller => 'newsletters' do
    resources :sektion, :as => 'newsletter_sections', :controller => 'newsletter_sections'
    resource :test_delivery
    resource :live_delivery
    get :admin, :on => :collection
  end
  match "/newsletters/hook/:secret", :to => 'newsletter_hooks#mailchimp_endpoint', :via => [:post, :get]
  match "/nyhetsbrev" => redirect("/sektionen/nyhetsbrev")
  
  resources :personer, :as => 'people', :controller => 'people' do
    resource :installningar, :controller => 'user_settings', :as => 'user_settings'
  end

  get '/installningar', :to => 'user_settings#edit_current', :as => 'settings'

  match '/nyheter/utkast/', :to => 'front_pages#show', :as => 'drafts', :drafts => true
  resources :nyheter, :as => 'posts', :controller => 'posts' do
    resources :kommentarer, :as => 'noises', :controller => 'noises'
  end
  resources :kommentarer, :as => 'noises', :controller => 'noises'
  
  match "/sok", :to => 'search#index', :as => 'search'
  
  resource :session, :as => 'sessions', :controller => 'sessions'
  match "/session/logga-ut", :to => 'sessions#destroy', :as => 'logout'

  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/val', :as => "nominees", :controller => 'nominees'
  match '/sektionen/naringsliv', :controller => 'naringsliv', :action => 'index', :as => 'naringsliv_index'
  resources '/sektionen/naringsliv/jobb', :controller => 'job_ads', :as => 'job_ads', :except => [:show]
  
  resources 'filnoder', :as => :file_nodes, :controller => 'file_nodes'
  
  resources 'textnoder', :as => :text_nodes, :controller => 'text_nodes' do
    resources :children, :controller => 'TextNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :filer, :as => :files, :controller => 'FileNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :versioner, :as => :versions, :controller => 'TextNodeVersions' do
      member do
        put :revert
      end
    end
    
    member do
      get :delete
    end
  end

  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'update', :via => :put
  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'add',:via=>:post
  match '/textnoder/:text_node_id/meny/delete/:id', :controller => 'TextNodeMenu', :action => 'delete', :via => :delete

  map.delete_text_node_menu '/textnoder/:text_node_id/meny/delete/:id'
  map.edit_text_node_menu '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'edit'
  
  match "/protokoll/:filename", :to => "protocols#show", :as => 'protocol'
  match "/protokoll", :to => "protocols#index", :as => 'protocols'

  # URL-mappning

  get '/kalender(/:year/:month)' => 'calendars#show', :as => :calendar,
    :month => nil, :year => nil,
    :constraints => { :month => /\d+/, :year => /\d+/ }
  get '/kalender.ics' => 'calendars#show', :as => :calendar_ics, :format => 'ics'
  resources '/kalender', :as => 'events', :controller => 'events', :except => :index

  resources '/sektionen/valtillfallen', :as => 'election_events', :controller => 'election_events'
  resources '/sektionen/val', :as => 'nominees', :controller => 'nominees'

  resources 'sektionen/funktionarsposter', :as => 'chapter_posts', :controller => 'chapter_posts'
  resources 'sektionen/funktionarer', :as => 'functionaries', :controller => 'functionaries' 

  resources :taggar, :as => 'tags', :controller => 'tags', :only => [:index, :destroy] do
    post :update_multiple
  end

  root :to => 'front_pages#show'
  match '/rss', :to => 'front_pages#rss'

  match "*url" => 'nodes#show'
end

app/models/person.rb
# encoding: utf-8
require 'ior/kth/users_groups/catalog_service'

class Person < ActiveRecord::Base
  has_one :kth_account, :dependent => :destroy
  has_one :morklaggning
  
  has_many :memberships
  has_many :roles, :through => :memberships
  has_many :newsletter_subscriptions do
    def active
      where(:state => 'active').first
    end
  end
  
  has_many :functionaries
  
  accepts_nested_attributes_for :newsletter_subscriptions
  
  validates_presence_of :first_name, :last_name, :email, :kth_username
  
  serialize :serialized_features

  default_scope includes(:morklaggning).where('people.deleted' => false, 'morklaggnings.person_id' => nil)
  
  searchable do
    text :name 
    text :kth_username
    text :chapter_posts_text, :stored => true do
      functionaries.map { |f| f.chapter_post.name }.join " "
  
    end
    
    text :committees_text, :stored => true do
      functionaries.map { |f| f.chapter_post.committee.present? && f.chapter_post.committee.name }.join " "
    end
  end
  
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def to_param
    kth_username
  end
  
  def to_s
    name
  end
  
  def self.find_or_import(ugid)
    Person.find_by_kth_ugid(ugid) or Person.import(ugid)
  end
  
  def self.current
    @current
  end
  
  def self.current=(current)
    @current = current
  end
  
  def anonymous?
    false
  end
  
  # Use some dynamic programming voodo for syntactic sugar
  Role.all.each do |role|
    define_method "#{role.to_s}?" do 
      has_role?(role.to_s)
    end
  end
  
  # Check if a user has a role.
  def has_role?(role)
    list ||= self.roles.map(&:name)
    list.include?(role.to_s) || list.include?('admin')
  end
  
  def features
    self.serialized_features ||= []
    serialized_features
  end
  
  def user_settings
    UserSettings.new(self)
  end
  
  def build_user_settings(attributes = {})
    @user_settings = UserSettings.new(self, attributes)
  end
  
  def has_feature?(feature)
    features.include?(feature.to_s)
  end
    
  # Imports a person into the system with the given UGID. 
  # Returns false if the person is not found.
  def self.import(ugid, catalog = Ior::KTH::UsersGroups::CatalogService.new)
    if (user = catalog.find(ugid)) and not Person.exists?(:kth_ugid => ugid)
      person = Person.new
      person.first_name = user.first_name
      person.last_name = user.last_name
      person.email = user.emails.include?("#{user.username}@kth.se") ? "#{user.username}@kth.se" : user.emails.first
      person.kth_username = user.username
      person.kth_ugid = ugid
      person.save!
      
      return person
    end
    
    return false
  end

  def gravatar_url
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.kth_username + '@kth.se')}?d=mm"
  end
  
  # Methods for compatibility with Student interface (fold)
  def sektion
    chapter
  end
  deprecate :sektion => 'use chapter instead'
  
  def username_nada
    kth_username
  end
  deprecate :username_nada => 'use kth_username'
  
  def username_kth
    kth_ugid
  end
  deprecate :username_kth => 'use kth_ugid'
  
  def uid
    kth_ugid
  end
  deprecate :uid => 'use kth_ugid'
  # (end)
  
  # Methods copied from Student (fold)
  def username
    return username_nada if !username_nada.nil?
    username_kth
  end

  #def email
  #  return username_nada + "@nada.kth.se" if !username_nada.nil?
  #  username_kth + "@kth.se"
  #end

  def plan
    if homedir
      if file_ok(homedir + "/.plan")
        File.open(homedir + "/.plan").to_a.join
      else
        ""
      end
    else
      "no homedir" # Har kvar som debug, man bör aldrig se den
    end
  end

  def file_ok(path)
    if File.exists?(path) && File.readable?(path)
      return true
    end
    false
  end
  
  # (end)

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  require_role "admin", :except => [:show, :zfinger_image, :edit, :update]

  def index
    @people = Person.all(:include => :roles).paginate(:page => params[:page])
  end

  def show
    @person = Person.find_by_kth_username(params[:id])
    if !@person && Person.current.admin?
      @person = Person.unscoped.find_by_kth_username(params[:id])
    end

    raise ActiveRecord::RecordNotFound if @person.nil?
  end
  
  def edit
    # Allow editing of deleted users
    @person = Person.unscoped.find_by_kth_username(params[:id])
    return access_denied unless Person.current.admin? || Person.current.id == @person.id
  end

  def update
    #Initialize values to nil, [] or {} unless set
    params[:person] = {} unless params[:person]
    #This might not be needed
    params[:person] = params[:person].each_value { |item| item = nil unless item }
    params[:person][:role_ids] = [] unless params[:person][:role_ids] 
    
    @person = Person.unscoped.find_by_kth_username(params[:id])
    return access_denied unless Person.current.admin? || Person.current.id == @person.id

    if Person.current.admin? 
      #Admin updates everything, including roles
      @person.update_attributes(params[:person])
    elsif Person.current.id == @person.id
      #A person can change his own data, but not roles
      @person.address = params[:person][:address]
      @person.phone = params[:person][:phone]
      @person.homepage = params[:person][:homepage]
      @person.nickname = params[:person][:nickname]
      @person.startyear = params[:person][:startyear]
      @person.personalemail = params[:person][:personalemail]
      @person.msn = params[:person][:msn]
      @person.xmpp = params[:person][:xmpp]
      @person.save
    end

    redirect_to @person
  end

  def destroy
    # Soft delete
    @person = Person.unscoped.find(params[:id])
    @person.deleted = true
    @person.save

    redirect_to(people_url)
  end
  
end

app/helpers/people_helper.rb
# encoding: utf-8
module PeopleHelper
  def zfinger_image(person, width = "256")
    url = "https://zfinger.datasektionen.se"
    image_tag("#{url}/user/#{person.kth_username}/image/#{width}",
              :alt => "zfinger-bild för #{person.to_s}",
              :title => "xfinger",
              :class => "xfinger")
  end
end

app/views/people/show.html.erb
<span style="float:right; margin-top: 10px"><a href="http://www.gravatar.com"><img src=http://www.gravatar.com/avatar/<%=Digest::MD5.hexdigest(@person.kth_username + "@kth.se")%>/></a></span>
<h2>
  <%= @person.first_name %> <%= @person.last_name %>
  <% unless Person.current.anonymous? %>
    (<%= @person.kth_username %>) 
  <% end -%>
</h2>

<% if Person.current.anonymous? -%>
  <p>Begränsad vy då du inte är inloggad.</p>
<% else -%>
  <p>
    <%= link_to "NADA hemsida", "http://www.nada.kth.se/~#{@person.kth_username}" %> | 
    <%= link_to @person.email, "mailto:#{@person.email}" %>
  </p>

  <table>
    <tr>
      <td><b>Startår:</b></td>
      <td><%= @person.try(:startyear) %></td>
    </tr>

    <tr>
      <td><b>Adress:</b></td>
      <td><%= @person.try(:address) %></td>
    </tr>

    <tr>
      <td><b>Telefon:</b></td>
      <td><%= @person.try(:phone) %></td>
    </tr>

    <tr>
      <td><b>Nick:</b></td>
      <td><%= @person.try(:nickname) %></td>
    </tr>

    <tr>
      <td><b>Personlig email:</b></td>
      <td><a href="mailto:<%=@person.try(:personalemail) %>"><%=@person.try(:personalemail) %></a></td>
    </tr>

    <tr>
      <td><b>Personlig hemsida:</b></td>
      <td><a href="<%=@person.try(:homepage) %>"><%=@person.try(:homepage) %></a></td>
    </tr>

    <tr>
      <td><b>Msn:</b></td>
      <td><%= @person.try(:msn) %></td>
    </tr>

    <tr>
      <td><b>Gtalk / XMPP:</b></td>
      <td><%= @person.try(:xmpp) %></td>
    </tr>
  </table>
  
  <p>
    <b>Plan:</b>
    <pre>
      <%=@person.plan %>
    </pre>
  </p>
  

  <h4>Xfinger</h4>
  <div class="xfinger"><%= image_tag xfinger_path(@person.username_nada), :width=>266, :alt => "Ingen bild" %></div>

<% end -%>

<% if Person.current.admin? or Person.current.id == @person.id %>
  <%= link_to 'Inställningar', person_user_settings_path(@person) %> | 
  <%= link_to 'Redigera', edit_person_path(@person) %>
<% end %>
<% if Person.current.admin? %>
  | <%= link_to 'Tillbaka', people_path %>
<% end -%>

<% if @person.functionaries.size > 0 %>

  <h4>Förtroendeuppdrag</h4>

  <table class="styled-table">
    <tr>
      <th>Post</th>
      <th>Från</th>
      <th>Till</th>
    </tr>
    <% for functionary in @person.functionaries.sorted do %>
      <tr>
        <td><%= link_to(functionary.chapter_post.name, functionary.chapter_post) %></td>
        <td><%= functionary.active_from %></td>
        <td><%= functionary.active_to %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/people/show.html.haml
= link_to "http://www.gravatar.com", :class => "profile gravatar" do
  = image_tag @person.gravatar_url, :alt => "gravatar"

%h2
  = @person.name
  - unless Person.current.anonymous?
    = "(#{@person.kth_username})"

- if Person.current.anonymous?
  %p Begränsad vy då du inte är inloggad.
- else

  %p
    = link_to "NADA hemsida", "http://www.nada.kth.se/~#{@person.kth_username}"
    != "&nbsp;|&nbsp;"
    = link_to @person.email, "mailto:#{@person.email}"
    - if Person.current.has_role?(:admin) or Person.current.id == @person.id
      != "&nbsp;|&nbsp;"
      = link_to 'Inställningar', person_user_settings_path(@person)
      != "&nbsp;|&nbsp;"
      = link_to 'Redigera', edit_person_path(@person)

  - if @person.deleted
    %p.deleted Denna person är markerad som borttagen.

  %table.credentials
    %tr
      %td.strong Startår:
      %td= @person.try :startyear
    %tr
      %td.strong Adress:
      %td= @person.try :address
    %tr
      %td.strong Telefon:
      %td= @person.try :phone
    %tr
      %td.strong Smeknamn:
      %td= @person.try :nickname
    %tr
      %td.strong Personlig epost:
      - if mailto = @person.try(:personalemail)
        %td= link_to mailto, "mailto:#{mailto}"
      - else
        %td
    %tr
      %td.strong Personlig hemsida:
      - if url = @person.try(:homepage)
        %td= link_to url, url 
      - else
        %td
    %tr
      %td.strong MSN:
      %td= @person.try :msn
    %tr
      %td.strong Gtalk / XMPP:
      %td= @person.try :xmpp

  - unless @person.plan.blank?
    %h3 Plan
    %pre.plan= @person.plan

  %h3 Zfinger
  = zfinger_image(@person, 256)

- if @person.functionaries.sorted.size > 0
  %h3 Förtroendeuppdrag
  %table
    %tr
      %th Post
      %th Från
      %th Till
    - @person.functionaries.sorted.each do |func|
      %tr
        %td= link_to func.chapter_post.name, func.chapter_post
        %td= func.active_from
        %td= func.active_to