config/routes.rb
Rails.application.routes.draw do |map|
  
  match "/admin", :to => 'admin#index'
  
  resources :blogs do
    resources :articles
  end
  
  resources :namnder, :as => 'committees', :controller => 'committees'
    
  get "/kontakt/:slug" => 'contact#index', :as => 'contact'
  post "/kontakt/:slug" => 'contact#send_mail'
  
  resources 'kth-konton', :as => 'kth_accounts', :controller => 'kth_accounts'
  
  resources :morklaggning, :as => 'morklaggnings', :controller => 'morklaggnings'
  
  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/nyhetsbrev', :as => 'newsletters', :controller => 'newsletters' do
    resources :sektion, :as => 'newsletter_sections', :controller => 'newsletter_sections'
    resource :test_delivery
    resource :live_delivery
    get :admin, :on => :collection
  end
  match "/newsletters/hook/:secret", :to => 'newsletter_hooks#mailchimp_endpoint', :via => [:post, :get]
  match "/nyhetsbrev" => redirect("/sektionen/nyhetsbrev")
  
  resources :personer, :as => 'people', :controller => 'people' do
    resource :installningar, :controller => 'user_settings', :as => 'user_settings'
  end

  get '/installningar', :to => 'user_settings#edit_current', :as => 'settings'

  match '/nyheter/utkast/', :to => 'front_pages#show', :as => 'drafts', :drafts => true
  resources :nyheter, :as => 'posts', :controller => 'posts' do
    resources :kommentarer, :as => 'noises', :controller => 'noises'
  end
  resources :kommentarer, :as => 'noises', :controller => 'noises'
  
  match "/sok", :to => 'search#index', :as => 'search'
  
  resource :session, :as => 'sessions', :controller => 'sessions'
  match "/session/logga-ut", :to => 'sessions#destroy', :as => 'logout'

  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/val', :as => "nominees", :controller => 'nominees'
  match '/sektionen/naringsliv', :controller => 'naringsliv', :action => 'index', :as => 'naringsliv_index'
  resources '/sektionen/naringsliv/jobb', :controller => 'job_ads', :as => 'job_ads', :except => [:show]
  
  resources 'filnoder', :as => :file_nodes, :controller => 'file_nodes'
  
  resources 'textnoder', :as => :text_nodes, :controller => 'text_nodes' do
    resources :children, :controller => 'TextNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :filer, :as => :files, :controller => 'FileNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :versioner, :as => :versions, :controller => 'TextNodeVersions' do
      member do
        put :revert
      end
    end
    
    member do
      get :delete
    end
  end

  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'update', :via => :put
  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'add',:via=>:post
  match '/textnoder/:text_node_id/meny/delete/:id', :controller => 'TextNodeMenu', :action => 'delete', :via => :delete

  map.delete_text_node_menu '/textnoder/:text_node_id/meny/delete/:id'
  map.edit_text_node_menu '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'edit'
  
  match "/protokoll/:filename", :to => "protocols#show", :as => 'protocol'
  match "/protokoll", :to => "protocols#index", :as => 'protocols'

  # URL-mappning

  get '/kalender(/:year/:month)' => 'calendars#show', :as => :calendar,
    :month => nil, :year => nil,
    :constraints => { :month => /\d+/, :year => /\d+/ }
  get '/kalender.ics' => 'calendars#show', :as => :calendar_ics, :format => 'ics'
  resources '/kalender', :as => 'events', :controller => 'events', :except => :index

  resources '/sektionen/valtillfallen', :as => 'election_events', :controller => 'election_events'
  resources '/sektionen/val', :as => 'nominees', :controller => 'nominees'

  resources 'sektionen/funktionarsposter', :as => 'chapter_posts', :controller => 'chapter_posts'
  resources 'sektionen/funktionarer', :as => 'functionaries', :controller => 'functionaries' 

  resources :taggar, :as => 'tags', :controller => 'tags', :only => [:index, :destroy] do
    post :update_multiple
  end

  root :to => 'front_pages#show'
  match '/rss', :to => 'front_pages#rss'

  match "*url" => 'nodes#show'
end

app/models/article.rb
# encoding: utf-8
class Article < ActiveRecord::Base
  belongs_to :blog
  belongs_to :author, :class_name => "Person", :foreign_key => "author_id"
  
  def to_param
    "#{id}-#{perma_name}"
  end
  
  protected
    def perma_name
      perma_name = title.downcase

      # convert öäå
      perma_name.gsub!(/äåÄÅ/, 'a')
      perma_name.gsub!(/öÖ/, 'o')
      
      # remove wierd characters
      perma_name.gsub!(/[^a-z\s]/, '')
      
      # convert whitespace
      perma_name.strip!
      perma_name.gsub!(/\s+/, '_')
            
      perma_name
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :load_blog
  
  require_role :editor, :except => [:show, :index]
  
  # GET /articles
  def index
    @articles = @blog.articles

    respond_to do |format|
      format.html { render :layout => layout_for(@blog)} # index.html.erb
      format.rss
    end
  end

  # GET /articles/1
  def show
    @article = @blog.articles.find(params[:id])

    respond_to do |format|
      format.html { render :layout => layout_for(@blog)} # show.html.erb
    end
  end

  # GET /articles/new
  def new
    @article = @blog.articles.new

    respond_to do |format|
      format.html { render :layout => layout_for(@blog)} # new.html.erb
    end
  end

  # GET /articles/1/edit
  def edit
    @article = @blog.articles.find(params[:id])

    respond_to do |format|
       format.html { render :layout => layout_for(@blog)}
     end
  end

  # POST /articles
  def create
    @article = @blog.articles.new(params[:article].merge(:author => Person.current))

    respond_to do |format|
      if @article.save
        flash[:notice] = 'Article was successfully created.'
        format.html { redirect_to(blog_article_path(@blog, @article)) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /articles/1
  def update
    @article = @blog.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        flash[:notice] = 'Article was successfully updated.'
        format.html { redirect_to(blog_article_path(@blog, @article)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /articles/1
  def destroy
    @article = @blog.articles.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(blog_articles_path(@blog)) }
    end
  end
  
  protected
  
  def layout_for(blog)
    blog.layout.blank? ? nil : blog.layout
  end
  
  def load_blog
    @blog = Blog.find_by_perma_name(params[:blog_id])
  end
end

app/views/articles/_article.html.erb
<div class="article">
  <h3><%= link_to article.title, [article.blog, article] %></h3>
  <p class="content">
    <%= textilize article.content %>
  </p>
  <% if Person.current.has_role?(:editor) %>
    <%= link_to 'Redigera', edit_blog_article_path(@blog, article) %> |
    <%= link_to 'Ta bort', [@blog, article], :method => :delete, :confirm => "Är du säker?" %>
  <% end %>

  <ul class="horizontal author right">
    <li class="author"><%= link_to article.author, article.author %></li>
    <li class="last">Skapad <%= article.created_at.strftime "%d %b" %></li>
  </ul>
</div>

app/views/articles/_form.html.erb
  <%= form.text_field :title %>
  <%= form.text_area :content, :rows => 20, :cols => 80 %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<% ior_form_for([@blog, @article]) do |f| %>
  <%= f.error_messages %>

  <%= render :partial => "form", :object => f %>

  <%= f.submit "Update" %>
<% end %>

<%= link_to 'Show', blog_article_path(@blog, @article) %> |
<%= link_to 'Back', blog_articles_path(@blog) %>

app/views/articles/index.html.erb
<h1 class="blog_title">
  <%= @blog.name %>
  <%= link_to image_tag('feed.png'), blog_articles_url(@blog, :format => :rss) %>
</h1>

<p><%= @blog.description %></p>

<% if Person.current.has_role?(:editor) %>
  <%= link_to "Nytt blogginlägg", new_blog_article_path(@blog) %>
<% end %>

<%= render :partial => "article", :collection => @articles %>

app/views/articles/new.html.erb
<h1>Nytt blogginlägg i <%= @blog %></h1>

<% ior_form_for([@blog, @article]) do |f| %>

  <%= render :partial => "form", :object => f %>

  <%= f.submit "Create" %>
<% end %>

<%= link_to 'Back', blog_articles_path(@blog) %>

app/views/articles/show.html.erb
<div class="article">
  <h3><%= @article.title %></h3>
  <p class="content">
    <%= textilize @article.content %>
  </p>
  <ul class="horizontal author right">
    <li class="author"><%= link_to @article.author, @article.author %></li>
    <li class="last">Skapad <%= @article.created_at.strftime "%d %b" %></li>
  </ul>
</div>

<% if Person.current.has_role?(:editor) %>
  <%= link_to 'Redigera', edit_blog_article_path(@blog, @article) %> |
  <%= link_to 'Ta bort', [@blog, @article], :method => :delete, :confirm => "Är du säker?" %> |
<% end %>
<%= link_to 'Tillbaka', blog_articles_path(@blog) %>