config/routes.rb
Rails.application.routes.draw do |map|
  
  match "/admin", :to => 'admin#index'
  
  resources :blogs do
    resources :articles
  end
  
  resources :namnder, :as => 'committees', :controller => 'committees'
    
  get "/kontakt/:slug" => 'contact#index', :as => 'contact'
  post "/kontakt/:slug" => 'contact#send_mail'
  
  resources 'kth-konton', :as => 'kth_accounts', :controller => 'kth_accounts'
  
  resources :morklaggning, :as => 'morklaggnings', :controller => 'morklaggnings'
  
  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/nyhetsbrev', :as => 'newsletters', :controller => 'newsletters' do
    resources :sektion, :as => 'newsletter_sections', :controller => 'newsletter_sections'
    resource :test_delivery
    resource :live_delivery
    get :admin, :on => :collection
  end
  match "/newsletters/hook/:secret", :to => 'newsletter_hooks#mailchimp_endpoint', :via => [:post, :get]
  match "/nyhetsbrev" => redirect("/sektionen/nyhetsbrev")
  
  resources :personer, :as => 'people', :controller => 'people' do
    resource :installningar, :controller => 'user_settings', :as => 'user_settings'
  end

  get '/installningar', :to => 'user_settings#edit_current', :as => 'settings'

  match '/nyheter/utkast/', :to => 'front_pages#show', :as => 'drafts', :drafts => true
  resources :nyheter, :as => 'posts', :controller => 'posts' do
    resources :kommentarer, :as => 'noises', :controller => 'noises'
  end
  resources :kommentarer, :as => 'noises', :controller => 'noises'
  
  match "/sok", :to => 'search#index', :as => 'search'
  
  resource :session, :as => 'sessions', :controller => 'sessions'
  match "/session/logga-ut", :to => 'sessions#destroy', :as => 'logout'

  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/val', :as => "nominees", :controller => 'nominees'
  match '/sektionen/naringsliv', :controller => 'naringsliv', :action => 'index', :as => 'naringsliv_index'
  resources '/sektionen/naringsliv/jobb', :controller => 'job_ads', :as => 'job_ads', :except => [:show]
  
  resources 'filnoder', :as => :file_nodes, :controller => 'file_nodes'
  
  resources 'textnoder', :as => :text_nodes, :controller => 'text_nodes' do
    resources :children, :controller => 'TextNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :filer, :as => :files, :controller => 'FileNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :versioner, :as => :versions, :controller => 'TextNodeVersions' do
      member do
        put :revert
      end
    end
    
    member do
      get :delete
    end
  end

  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'update', :via => :put
  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'add',:via=>:post
  match '/textnoder/:text_node_id/meny/delete/:id', :controller => 'TextNodeMenu', :action => 'delete', :via => :delete

  map.delete_text_node_menu '/textnoder/:text_node_id/meny/delete/:id'
  map.edit_text_node_menu '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'edit'
  
  match "/protokoll/:filename", :to => "protocols#show", :as => 'protocol'
  match "/protokoll", :to => "protocols#index", :as => 'protocols'

  # URL-mappning

  get '/kalender(/:year/:month)' => 'calendars#show', :as => :calendar,
    :month => nil, :year => nil,
    :constraints => { :month => /\d+/, :year => /\d+/ }
  get '/kalender.ics' => 'calendars#show', :as => :calendar_ics, :format => 'ics'
  resources '/kalender', :as => 'events', :controller => 'events', :except => :index

  resources '/sektionen/valtillfallen', :as => 'election_events', :controller => 'election_events'
  resources '/sektionen/val', :as => 'nominees', :controller => 'nominees'

  resources 'sektionen/funktionarsposter', :as => 'chapter_posts', :controller => 'chapter_posts'
  resources 'sektionen/funktionarer', :as => 'functionaries', :controller => 'functionaries' 

  resources :taggar, :as => 'tags', :controller => 'tags', :only => [:index, :destroy] do
    post :update_multiple
  end

  root :to => 'front_pages#show'
  match '/rss', :to => 'front_pages#rss'

  match "*url" => 'nodes#show'
end

app/views/job_ads/naringsliv_index.html.erb
<%= include_node "/sektionen/namnder/naringsliv" %>

<h2>Jobbannonser</h2>


<% form_tag(naringsliv_index_path, :method => :get) do %>
  <%= label_tag "full_time", "Heltid" %>
  <%= check_box_tag "full_time", 1, params[:full_time] %>
  
  <%= label_tag "part_time", "Deltid" %>
  <%= check_box_tag "part_time", 1, params[:part_time] %>
  
  <%= label_tag "thesis", "Exjobb" %>
  <%= check_box_tag "thesis", 1, params[:thesis] %>
  
  <%= submit_tag "Filtrera"%>
<% end -%>


<% for ad in @job_ads %>
  <div>
    <h3><%= ad.title %></h3>
    
    <p style="font-style: italic"><%= ad.company %></p>
    <p><%= ad.description %></p>
    
    <% if Person.current.pr? %>
      <ul class="horizontal author left">
        <li><%= link_to 'Redigera', edit_job_ad_path(ad) %></li>
        <li class="last"><%= link_to 'Ta bort', ad, :method => :delete, :confirm => 'Är du säker på att du vill ta bort den här nyheten?' %></li>
      </ul>
    <% end %>
    
    <ul class="horizontal author right">
      <li><%= link_to ad.created_by, person_path(ad.created_by) %></li>
      <li>Skapad <%= ad.created_at.strftime "%d %b" %></li>
      <li>Förfaller <%= ad.expires_at.strftime "%d %b"%></li>
      <li class="last"><%= ad.types.join(", ") %></li>
    </ul>
    
  </div>
  
  <div class="separator"></div>
<% end -%>

<% if Person.current.pr? %>
  <%= link_to 'Ny Jobbannons', new_job_ad_path %>
<% end -%>