config/routes.rb
Rails.application.routes.draw do |map|
  
  match "/admin", :to => 'admin#index'
  
  resources :blogs do
    resources :articles
  end
  
  resources :namnder, :as => 'committees', :controller => 'committees'
    
  get "/kontakt/:slug" => 'contact#index', :as => 'contact'
  post "/kontakt/:slug" => 'contact#send_mail'
  
  resources 'kth-konton', :as => 'kth_accounts', :controller => 'kth_accounts'
  
  resources :morklaggning, :as => 'morklaggnings', :controller => 'morklaggnings'
  
  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/nyhetsbrev', :as => 'newsletters', :controller => 'newsletters' do
    resources :sektion, :as => 'newsletter_sections', :controller => 'newsletter_sections'
    resource :test_delivery
    resource :live_delivery
    get :admin, :on => :collection
  end
  match "/newsletters/hook/:secret", :to => 'newsletter_hooks#mailchimp_endpoint', :via => [:post, :get]
  match "/nyhetsbrev" => redirect("/sektionen/nyhetsbrev")
  
  resources :personer, :as => 'people', :controller => 'people' do
    resource :installningar, :controller => 'user_settings', :as => 'user_settings'
  end

  get '/installningar', :to => 'user_settings#edit_current', :as => 'settings'

  match '/nyheter/utkast/', :to => 'front_pages#show', :as => 'drafts', :drafts => true
  resources :nyheter, :as => 'posts', :controller => 'posts' do
    resources :kommentarer, :as => 'noises', :controller => 'noises'
  end
  resources :kommentarer, :as => 'noises', :controller => 'noises'
  
  match "/sok", :to => 'search#index', :as => 'search'
  
  resource :session, :as => 'sessions', :controller => 'sessions'
  match "/session/logga-ut", :to => 'sessions#destroy', :as => 'logout'

  resources 'sektionen/funktionarer', :as => "functionaries", :controller => 'functionaries'
  resources 'sektionen/val', :as => "nominees", :controller => 'nominees'
  match '/sektionen/naringsliv', :controller => 'naringsliv', :action => 'index', :as => 'naringsliv_index'
  resources '/sektionen/naringsliv/jobb', :controller => 'job_ads', :as => 'job_ads', :except => [:show]
  
  resources 'filnoder', :as => :file_nodes, :controller => 'file_nodes'
  
  resources 'textnoder', :as => :text_nodes, :controller => 'text_nodes' do
    resources :children, :controller => 'TextNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :filer, :as => :files, :controller => 'FileNodeChildren', :path_prefix => 'textnoder/:node_id'
    resources :versioner, :as => :versions, :controller => 'TextNodeVersions' do
      member do
        put :revert
      end
    end
    
    member do
      get :delete
    end
  end

  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'update', :via => :put
  match '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'add',:via=>:post
  match '/textnoder/:text_node_id/meny/delete/:id', :controller => 'TextNodeMenu', :action => 'delete', :via => :delete

  map.delete_text_node_menu '/textnoder/:text_node_id/meny/delete/:id'
  map.edit_text_node_menu '/textnoder/:text_node_id/meny', :controller => 'TextNodeMenu', :action => 'edit'
  
  match "/protokoll/:filename", :to => "protocols#show", :as => 'protocol'
  match "/protokoll", :to => "protocols#index", :as => 'protocols'

  # URL-mappning

  get '/kalender(/:year/:month)' => 'calendars#show', :as => :calendar,
    :month => nil, :year => nil,
    :constraints => { :month => /\d+/, :year => /\d+/ }
  get '/kalender.ics' => 'calendars#show', :as => :calendar_ics, :format => 'ics'
  resources '/kalender', :as => 'events', :controller => 'events', :except => :index

  resources '/sektionen/valtillfallen', :as => 'election_events', :controller => 'election_events'
  resources '/sektionen/val', :as => 'nominees', :controller => 'nominees'

  resources 'sektionen/funktionarsposter', :as => 'chapter_posts', :controller => 'chapter_posts'
  resources 'sektionen/funktionarer', :as => 'functionaries', :controller => 'functionaries' 

  resources :taggar, :as => 'tags', :controller => 'tags', :only => [:index, :destroy] do
    post :update_multiple
  end

  root :to => 'front_pages#show'
  match '/rss', :to => 'front_pages#rss'

  match "*url" => 'nodes#show'
end

app/controllers/front_pages_controller.rb
class FrontPagesController < ApplicationController
  def show
    @posts = (params[:drafts] ? Post.drafts : Post.published)
    
    if params[:tags]
      @posts = @posts.tagged_with(params[:tags].gsub('%', ''))
      @active_tags = ActsAsTaggableOn::TagList.from(params[:tags])
    end
    
    page = params[:page].to_i; page = 1 if page < 1
    @posts = @posts.paginate(:page => page, :per_page => 5)

    @menu_template = "nyheter"

    now = Time.now
    @events = Event.between(
      now.beginning_of_day,
      now + Rails.application.settings[:show_n_days_in_calendar].days
    ).order(:starts_at.asc).limit(5)
    
    unless Person.current.anonymous?  
      @user_settings = Person.current.build_user_settings
    end

    @tags = Rails.cache.fetch('tag_list') do
      Post.published.tag_counts_on(:categories).order("count desc").all
    end
    # apparentely the cache process freezes the object... this ugly hack circumvents that
    @tags = @tags.dup if @tags.frozen?

    # fix for exception raising when odd formats are requeted
    if request.format != Mime::HTML
      raise ActionController::RoutingError, "Invalid output format (#{params[:format].inspect}) requested."
    end
  end
  
  def rss
    @posts = Post.published
    
    if params[:tags]
      @posts = @posts.tagged_with(params[:tags])
      @active_tags = ActsAsTaggableOn::TagList.from(params[:tags])
    end
    
    @posts = @posts.limit(20)
  end
end

app/views/front_pages/_calendar.html.haml
.events
  %h2 Agenda
  %p Här är datasektionens agenda för den närmaste tiden.
  - @events.each do |calendar_post|
    .event
      %p.description= link_to calendar_post, calendar_post
      %p.meta.time
        = l(calendar_post.starts_at, :format => "%A").capitalize + "en"
        %span.dim den
        = l calendar_post.starts_at, :format => "%e %b"
        - if !calendar_post.all_day?
          %span.dim kl.
          = l calendar_post.starts_at, :format => "%H:%M"

  %p== Se alla event i #{link_to "kalendern", calendar_path}. Kalendern finns även i ICS-format så att du kan lägga till den i t.ex. Google Calendar.

app/views/front_pages/_jobs.html.haml
.jobs
  %h2 Jobb?

  %p
    Är du sugen på sommarjobb, exjobb, traineeplats eller har du mot förmodan tagit examen och är sugen på ett heltidsjobb? Ta en sväng förbi Datasektionens egen jobbportal och se om något passar!
    = succeed('.') do
      = link_to 'Jobbportalen hittar ni här', "http://djobb.se/"

app/views/front_pages/_submenu.html.haml
%ul
  %li 
    %span
      - if params[:tags]
        %span= link_to "Alla", root_path
      - else
        %b= link_to "Alla", root_path
      %span.dim= "(#{Post.count})"
  - ActsAsTaggableOn::Tag.all.each do |tag|
    %li
      - if params[:tags] == tag.name
        %b= link_to tag, root_path(:tags => tag.name)
      - else
        %span= link_to tag, root_path(:tags => tag.name)
      %span.dim= "(#{tag.taggings.count})"

app/views/front_pages/show.html.haml
- title "Nyheter"

- content_for :additional_content do 
  %h3.sub &nbsp;

  = render :partial => "front_pages/calendar"
  = render :partial => "front_pages/jobs"
  = render :partial => "twitter/twitter"

#news
  - @notification = include_node("/_ugly_hack_welcome")
  - unless @notification.empty?
    .notification= @notification
  - unless Person.current.anonymous? || Person.current.has_chosen_settings?
    #first_time_welcome.notification
      = include_node("/first_time_welcome")
      
      = simple_form_for([Person.current, @user_settings], :url => person_user_settings_path(Person.current, @user_settings)) do |f|
        = f.input :newsletter, :as => :boolean, :label => 'Nyhetsbrev'
        = f.submit :value => 'Spara inställningar'

  %h3.sub
    - if params[:drafts]
      Utkast
    - elsif params[:tags]
      Nyheter taggade:
      %strong= params[:tags]
    - else
      Alla nyheter

  = render :partial => 'posts/post', :collection => @posts
  
  = will_paginate(@posts)